version: "2" # required to adjust maintainability checks
exclude_patterns:
    - "src/templates/*.js"
    - "src/hexapod/plotter.js"
    - "src/serviceWorker.js "
    - "src/tests/*"

checks:
    argument-count:
        config:
            threshold: 6
    complex-logic:
        config:
            threshold: 5
    file-lines:
        config:
            threshold: 250
    method-complexity:
        config:
            threshold: 6
    method-count:
        config:
            threshold: 20
    method-lines:
        config:
            threshold: 25
    nested-control-flow:
        config:
            threshold: 4
    return-statements:
        config:
            threshold: 5
    similar-code:
        config:
            threshold: # language-specific defaults. an override will affect all languages.
    identical-code:
        config:
            threshold: # language-specific defaults. an override will affect all languages.
